/**
 * bump-build.js — Auto-increment build number and set VITE_ env vars.
 * Reads/writes .build-number file. Sets VITE_APP_VERSION and VITE_BUILD_ID.
 */
import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');
const buildFile = resolve(root, '.build-number');
const pkg = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf8'));

// Read or init build number
let buildNum = 1;
try {
  buildNum = parseInt(readFileSync(buildFile, 'utf8').trim(), 10) + 1;
} catch { /* first build */ }

writeFileSync(buildFile, String(buildNum));

// Build ID: YYYYMMDD.buildNum
const now = new Date();
const date = now.toISOString().slice(0, 10).replace(/-/g, '');
const buildId = `${date}.${buildNum}`;

// Set env vars for Vite
process.env.VITE_APP_VERSION = pkg.version;
process.env.VITE_BUILD_ID = buildId;

// Write .env.build (Vite loads .env* files automatically)
const envContent = `# Auto-generated by bump-build.js — do not edit
VITE_APP_VERSION=${pkg.version}
VITE_BUILD_ID=${buildId}
`;
writeFileSync(resolve(root, '.env.build'), envContent);

console.log(`Build: v${pkg.version} #${buildId}`);
